"""Verified and reviewed country metadata for artists in the master dataset."""

import ast
from functools import lru_cache
from pathlib import Path


ARTIST_COUNTRIES = {
    "031choppa": ("South Africa", "ZA"),
    "2wentysixx": ("Tanzania", "TZ"),
    "a$ap rocky": ("United States", "US"),
    "abongo jakabwana": ("Kenya", "KE"),
    "addeh prince": ("Kenya", "KE"),
    "aidonia": ("Jamaica", "JM"),
    "alex warren": ("United States", "US"),
    "audrey nuna": ("United States", "US"),
    "ayetian": ("Jamaica", "JM"),
    "babalwa m": ("South Africa", "ZA"),
    "baby keem": ("United States", "US"),
    "bad bunny": ("Puerto Rico", "PR"),
    "barry jhay": ("Nigeria", "NG"),
    "bella shmurda": ("Nigeria", "NG"),
    "brandy maina": ("Kenya", "KE"),
    "brent faiyaz": ("United States", "US"),
    "bts": ("South Korea", "KR"),
    "calad": ("Tanzania", "TZ"),
    "chella": ("Nigeria", "NG"),
    "ciara": ("United States", "US"),
    "ciza": ("South Africa", "ZA"),
    "clipse": ("United States", "US"),
    "collo blue": ("Kenya", "KE"),
    "countree hype": ("Kenya", "KE"),
    "cris mj": ("Chile", "CL"),
    "d-voice": ("Tanzania", "TZ"),
    "daniel caesar": ("Canada", "CA"),
    "diameter pallet": ("Kenya", "KE"),
    "dj 4kerty": ("Nigeria", "NG"),
    "dj cheem": ("United States", "US"),
    "dj maphorisa": ("South Africa", "ZA"),
    "dj smallz": ("South Africa", "ZA"),
    "doja cat": ("United States", "US"),
    "dominic fike": ("United States", "US"),
    "dorcas": ("Rwanda", "RW"),
    "dufla": ("Kenya", "KE"),
    "devrix da fubu": ("Kenya", "KE"),
    "eddy g": ("Jamaica", "JM"),
    "eemoh": ("South Africa", "ZA"),
    "ejae": ("United States", "US"),
    "elevation worship": ("United States", "US"),
    "elisha toto": ("Tanzania", "TZ"),
    "element eleéeh": ("Rwanda", "RW"),
    "enny man da guitar": ("South Africa", "ZA"),
    "esdeekid": ("United Kingdom", "GB"),
    "fave": ("Nigeria", "NG"),
    "fik fameica": ("Uganda", "UG"),
    "floroyymenor": ("Chile", "CL"),
    "floyymenor": ("Chile", "CL"),
    "fola": ("Nigeria", "NG"),
    "gajendra verma": ("India", "IN"),
    "giveon": ("United States", "US"),
    "gl_ceejay": ("South Africa", "ZA"),
    "goon flavour": ("South Africa", "ZA"),
    "gradine toto": ("Kenya", "KE"),
    "harry styles": ("United Kingdom", "GB"),
    "huntr/x": ("South Korea", "KR"),
    "intence": ("Jamaica", "JM"),
    "isaiah rashad": ("United States", "US"),
    "ivanny": ("Tanzania", "TZ"),
    "jackboys": ("United States", "US"),
    "jae5": ("United Kingdom", "GB"),
    "jahvillani": ("Jamaica", "JM"),
    "jazzworx": ("South Africa", "ZA"),
    "jazzwrld": ("South Africa", "ZA"),
    "jeleel!": ("United States", "US"),
    "jetti": ("United States", "US"),
    "kehlani": ("United States", "US"),
    "kondela": ("Kenya", "KE"),
    "kahuti": ("Kenya", "KE"),
    "kinoti": ("Kenya", "KE"),
    "kpop demon hunters cast": ("South Korea", "KR"),
    "kunatino music": ("Zimbabwe", "ZW"),
    "kunmie": ("Nigeria", "NG"),
    "kusslove": ("Tanzania", "TZ"),
    "lady maureen": ("Kenya", "KE"),
    "lava lava": ("Tanzania", "TZ"),
    "leehleza": ("South Africa", "ZA"),
    "licky tones": ("Kenya", "KE"),
    "lil baby": ("United States", "US"),
    "lilmaina": ("Kenya", "KE"),
    "maandy": ("Kenya", "KE"),
    "mad g": ("Kenya", "KE"),
    "mahoo": ("South Africa", "ZA"),
    "mawhoo": ("South Africa", "ZA"),
    "mariah the scientist": ("United States", "US"),
    "malice": ("United States", "US"),
    "michael jackson": ("United States", "US"),
    "minister james": ("Tanzania", "TZ"),
    "myztro": ("South Africa", "ZA"),
    "mugs.roze": ("Jamaica", "JM"),
    "nameless": ("Kenya", "KE"),
    "nasty c": ("South Africa", "ZA"),
    "nathaniel bassey": ("Nigeria", "NG"),
    "neha kakkar": ("India", "IN"),
    "nigy boy": ("Jamaica", "JM"),
    "nine vicious": ("United States", "US"),
    "nk_njoroge": ("Kenya", "KE"),
    "odumodublvck": ("Nigeria", "NG"),
    "offset": ("United States", "US"),
    "okello max": ("Kenya", "KE"),
    "olamide": ("Nigeria", "NG"),
    "popcaan": ("Jamaica", "JM"),
    "pusha t": ("United States", "US"),
    "raye": ("United Kingdom", "GB"),
    "rei ami": ("United States", "US"),
    "rymey": ("Jamaica", "JM"),
    "rvssian": ("Jamaica", "JM"),
    "saja boys": ("South Korea", "KR"),
    "sarz": ("Nigeria", "NG"),
    "scotts maphuma": ("South Africa", "ZA"),
    "silent addy": ("Ghana", "GH"),
    "skeng": ("Jamaica", "JM"),
    "sun-el musician": ("South Africa", "ZA"),
    "suns3t": ("South Africa", "ZA"),
    "soul touch brand": ("Kenya", "KE"),
    "t.i blaze": ("Nigeria", "NG"),
    "the second voice": ("Kenya", "KE"),
    "teebone": ("Jamaica", "JM"),
    "thukuthela": ("South Africa", "ZA"),
    "tommy lee": ("Jamaica", "JM"),
    "tml vibez": ("Nigeria", "NG"),
    "vestine": ("Rwanda", "RW"),
    "vic west": ("Kenya", "KE"),
    "udede": ("Kenya", "KE"),
    "unjaps": ("South Africa", "ZA"),
    "urban chords": ("Nigeria", "NG"),
    "unspoken salaton": ("Kenya", "KE"),
    "wapendwa muziki": ("Kenya", "KE"),
    "x.o": ("South Africa", "ZA"),
    "xania monet": ("United States", "US"),
    "xduppy": ("South Africa", "ZA"),
    "young thug": ("United States", "US"),
    "ywaya tajiri": ("Kenya", "KE"),
    "zaituni": ("Tanzania", "TZ"),
    "zinedinexsguche": ("South Africa", "ZA"),
    "mikeeysmind": ("Germany", "DE"),
}


@lru_cache(maxsize=1)
def _base_artist_countries():
    command_path = Path(__file__).parent / "management" / "commands" / "update_artist_countries.py"
    module = ast.parse(command_path.read_text(encoding="utf-8"))
    for node in module.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "ARTIST_COUNTRIES" for target in node.targets
        ):
            base_countries = ast.literal_eval(node.value)
            return {str(name).strip().casefold(): value for name, value in base_countries.items()}
    return {}


def artist_country(name):
    key = str(name or "").strip().casefold()
    return ARTIST_COUNTRIES.get(key) or _base_artist_countries().get(key)
