import { useEffect, useMemo, useState } from "react";
import { cmsApi, getResults, qs } from "../api";
import DataTable from "../components/DataTable";
import SearchBar from "../components/SearchBar";
import FormModal from "../components/FormModal";

const configs = {
  artists: { title: "Artists", endpoint: "/artists/", search: true, fields: ["name", "display_name", "country", "country_code", "genre", "artist_type", "status"], columns: [{key:"name",label:"Artist"},{key:"country_code",label:"Country"},{key:"genre",label:"Genre"},{key:"total_releases",label:"Releases"},{key:"status",label:"Status"}], form: [{name:"name",label:"Artist name"},{name:"display_name",label:"Display name"},{name:"country",label:"Country"},{name:"country_code",label:"Country code"},{name:"genre",label:"Genre"},{name:"artist_type",label:"Artist type"},{name:"status",label:"Status"}] },
  songs: { title: "Songs", endpoint: "/releases/", params:{chart_type:"singles"}, fields: [], columns: [{key:"title",label:"Song"},{key:"artist_name",label:"Artist"},{key:"country_code",label:"Country"},{key:"release_year",label:"Year"},{key:"status",label:"Status"}], form: releaseForm("singles") },
  albums: { title: "Albums", endpoint: "/releases/", params:{chart_type:"albums"}, columns: [{key:"title",label:"Album"},{key:"artist_name",label:"Artist"},{key:"country_code",label:"Country"},{key:"release_year",label:"Year"},{key:"status",label:"Status"}], form: releaseForm("albums") },
  countries: { title: "Countries", endpoint: "/countries/", columns: [{key:"name",label:"Country"},{key:"code",label:"Code"},{key:"region",label:"Region"},{key:"active",label:"Active"}], form: [{name:"name",label:"Country"},{name:"code",label:"Code"},{name:"region",label:"Region"},{name:"flag",label:"Flag/Initial"},{name:"display_order",label:"Order",type:"number"}] },
  platforms: { title: "Platforms", endpoint: "/platforms/", columns: [{key:"name",label:"Platform"},{key:"short_name",label:"Short"},{key:"color",label:"Color"},{key:"max_chart_size",label:"Max"},{key:"active",label:"Active"}], form: [{name:"name",label:"Name"},{name:"slug",label:"Slug"},{name:"short_name",label:"Short name"},{name:"color",label:"Color"},{name:"brand_color",label:"Brand color"},{name:"max_chart_size",label:"Max chart size",type:"number"},{name:"points_base",label:"Points base",type:"number"}] },
  news: { title: "News CMS", endpoint: "/news/", columns: [{key:"title",label:"Headline"},{key:"category",label:"Category"},{key:"author",label:"Author"},{key:"status",label:"Status"},{key:"updated_at",label:"Updated",render:(r)=>new Date(r.updated_at).toLocaleDateString()}], form: [{name:"title",label:"Headline"},{name:"slug",label:"Slug"},{name:"subheadline",label:"Subheadline"},{name:"category",label:"Category",type:"select",options:["chart_news","milestones","new_releases","industry_news","artist_news","awards","certifications","records","interviews","editorials"].map(v=>({value:v,label:v.replace(/_/g," ")}))},{name:"author",label:"Author"},{name:"excerpt",label:"Excerpt",type:"textarea"},{name:"body",label:"Body",type:"textarea"},{name:"status",label:"Status"}] },
  charts: { title: "Charts", endpoint: "/charts/", columns: [{key:"label",label:"Month"},{key:"chart_type",label:"Type"},{key:"combined_entries_count",label:"Combined entries"},{key:"status",label:"Status"},{key:"locked",label:"Locked"}], form: [{name:"year",label:"Year",type:"number"},{name:"month",label:"Month",type:"number"},{name:"chart_type",label:"Chart type",type:"select",options:[{value:"singles",label:"Singles"},{value:"albums",label:"Albums"}]},{name:"status",label:"Status"}] },
  certifications: { title: "Certifications", endpoint: "/certifications/", columns: [{key:"title",label:"Release"},{key:"artist",label:"Artist"},{key:"level",label:"Level"},{key:"total_points",label:"Points"},{key:"is_official",label:"Official"}], form: [{name:"release",label:"Release ID",type:"number"},{name:"level",label:"Level",type:"select",options:[{value:"gold",label:"Gold"},{value:"platinum",label:"Platinum"},{value:"diamond",label:"Diamond"}]},{name:"total_points",label:"Points",type:"number"}] },
  media: { title: "Media Library", endpoint: "/media/", columns: [{key:"title",label:"Title"},{key:"folder",label:"Folder"},{key:"alt_text",label:"Alt text"},{key:"uploaded_at",label:"Uploaded",render:(r)=>new Date(r.uploaded_at).toLocaleDateString()}], form: [{name:"title",label:"Title"},{name:"folder",label:"Folder"},{name:"alt_text",label:"Alt text"},{name:"usage_notes",label:"Usage notes",type:"textarea"}] },
  settings: { title: "Settings", endpoint: "/settings/", columns: [{key:"key",label:"Key"},{key:"group",label:"Group"},{key:"value",label:"Value",render:(r)=>JSON.stringify(r.value)}], form: [{name:"key",label:"Key"},{name:"group",label:"Group"},{name:"description",label:"Description"},{name:"value",label:"Value JSON",type:"json"}] },
  users: { title: "Users & Roles", endpoint: "/users/", columns: [{key:"username",label:"Username"},{key:"email",label:"Email"},{key:"profile",label:"Role",render:(r)=>r.profile?.role_label || "—"},{key:"is_active",label:"Active"}], form: [{name:"username",label:"Username"},{name:"email",label:"Email"},{name:"first_name",label:"First name"},{name:"last_name",label:"Last name"},{name:"role",label:"Role",type:"select",options:["super_admin","admin","editor","data_editor","news_editor","reviewer","viewer"].map(v=>({value:v,label:v.replace(/_/g," ")}))},{name:"password",label:"Password"}] },
  reports: { title: "Reports", endpoint: "/reports/", columns: [{key:"module",label:"Module"},{key:"issue_type",label:"Issue"},{key:"severity",label:"Severity"},{key:"description",label:"Description"},{key:"status",label:"Status"}], form: [{name:"module",label:"Module"},{name:"issue_type",label:"Issue type"},{name:"severity",label:"Severity"},{name:"description",label:"Description",type:"textarea"},{name:"status",label:"Status"}] },
  audit: { title: "Audit Logs", endpoint: "/audit-logs/", readOnly:true, columns: [{key:"created_at",label:"Time",render:(r)=>new Date(r.created_at).toLocaleString()},{key:"user_name",label:"User"},{key:"action",label:"Action"},{key:"module",label:"Module"},{key:"object_repr",label:"Object"}] },
  backups: { title: "Backups", endpoint: "/backups/", columns: [{key:"status",label:"Status"},{key:"file",label:"File"},{key:"created_at",label:"Created",render:(r)=>new Date(r.created_at).toLocaleString()}], form: [{name:"status",label:"Status"},{name:"notes",label:"Notes",type:"textarea"}] },
};

function releaseForm(chartType){ return [{name:"title",label:"Title"},{name:"artist",label:"Artist ID",type:"number"},{name:"chart_type",label:"Chart type",type:"select",options:[{value:chartType,label:chartType}]},{name:"canonical_title",label:"Canonical title"},{name:"featured_artists",label:"Featured artists"},{name:"country_code",label:"Country code"},{name:"release_year",label:"Release year",type:"number"},{name:"genre",label:"Genre"},{name:"label",label:"Label"},{name:"distributor",label:"Distributor"},{name:"status",label:"Status"}]; }

export default function ResourcePage({ type }) {
  const config = configs[type] || configs.artists;
  const [rows, setRows] = useState([]), [search, setSearch] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState(""), [modal, setModal] = useState(false), [editing, setEditing] = useState(null);
  const params = useMemo(() => ({ ...(config.params || {}), search }), [config, search]);
  async function load(){ setLoading(true); setError(""); try { setRows(getResults(await cmsApi.get(`${config.endpoint}${qs(params)}`))); } catch(e){ setError(e.message); } finally { setLoading(false); }}
  useEffect(()=>{ load(); }, [type, search]);
  async function save(form){ try { if(editing?.id) await cmsApi.patch(`${config.endpoint}${editing.id}/`, form); else await cmsApi.post(config.endpoint, form); setModal(false); setEditing(null); load(); } catch(e){ setError(e.message); }}
  return <section><div className="cms-page-head"><div><h1>{config.title}</h1><p>Manage {config.title.toLowerCase()} from the CMS.</p></div>{!config.readOnly && <button className="cms-btn" onClick={()=>{setEditing(null);setModal(true);}}>Add new</button>}</div>{error && <div className="cms-alert error">{error}</div>}<div className="cms-toolbar"><SearchBar value={search} onChange={setSearch} placeholder={`Search ${config.title.toLowerCase()}...`} /></div>{loading ? <div className="cms-empty">Loading...</div> : <DataTable columns={config.columns} rows={rows} onRowClick={config.readOnly ? null : (row)=>{setEditing(row);setModal(true);}} />}<FormModal open={modal} title={`${editing ? "Edit" : "Create"} ${config.title}`} fields={config.form || []} initial={editing || defaultInitial(config.form)} onSubmit={save} onClose={()=>setModal(false)} /></section>;
}
function defaultInitial(fields=[]){ return Object.fromEntries(fields.map(f=>[f.name, f.name==='status'?'active':''])); }
