# Generated by Django 6.0.4 on 2026-05-02 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#888888', max_length=7)),
                ('chart_size', models.IntegerField(default=100, help_text='Top N chart size e.g. 100 or 200')),
                ('points_base', models.IntegerField(default=101, help_text='Points = base - position')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('chart_type', models.CharField(choices=[('singles', 'Singles'), ('albums', 'Albums')], max_length=10)),
                ('label', models.CharField(help_text="e.g. 'October 2024'", max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month', 'chart_type')},
            },
        ),
        migrations.CreateModel(
            name='NormalizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('artist', 'Artist'), ('title', 'Title')], max_length=10)),
                ('raw_value', models.CharField(max_length=500)),
                ('canonical_value', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rule_type', 'raw_value'],
                'unique_together': {('rule_type', 'raw_value')},
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('chart_type', models.CharField(choices=[('singles', 'Singles'), ('albums', 'Albums')], max_length=10)),
                ('canonical_title', models.CharField(help_text='Normalized title for deduplication', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='charts.artist')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('canonical_title', 'artist', 'chart_type')},
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('chart_news', 'Chart News'), ('artist_spotlight', 'Artist Spotlight'), ('albums', 'Albums'), ('analytics', 'Analytics'), ('announcement', 'Announcement')], max_length=20)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('emoji', models.CharField(default='🎵', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charts.artist')),
                ('related_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charts.release')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('singles', 'Singles'), ('albums', 'Albums')], max_length=10)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('file', models.FileField(upload_to='uploads/weekly/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
                ('duplicates_dropped', models.IntegerField(default=0)),
                ('entries_processed', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-week'],
                'unique_together': {('chart_type', 'year', 'month', 'week')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('weeks_on_chart', models.IntegerField(default=1)),
                ('platform_count', models.IntegerField(default=1, help_text='Number of platforms charted on (combined only)')),
                ('peak_rank', models.IntegerField(default=1)),
                ('prev_rank', models.IntegerField(blank=True, help_text='Rank in previous month', null=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='charts.monthlychart')),
                ('platform', models.ForeignKey(blank=True, help_text='Null = combined chart', null=True, on_delete=django.db.models.deletion.CASCADE, to='charts.platform')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.release')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('chart', 'platform', 'release')},
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ngoma', 'Ngoma'), ('gold', 'Ngoma Gold'), ('platinum', 'Ngoma Platinum'), ('diamond', 'Ngoma Diamond')], max_length=20)),
                ('certified_at', models.DateTimeField(auto_now_add=True)),
                ('total_points', models.IntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='charts.release')),
            ],
            options={
                'ordering': ['-certified_at'],
                'unique_together': {('release', 'level')},
            },
        ),
        migrations.CreateModel(
            name='PlatformChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('raw_title', models.CharField(help_text='Original title from raw data', max_length=500)),
                ('raw_artist', models.CharField(help_text='Original artist from raw data', max_length=500)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.platform')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.release')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='charts.weeklyupload')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('upload', 'platform', 'position')},
            },
        ),
    ]
