# Generated by Django 4.2.30 on 2026-06-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='platform',
            name='chart_size',
            field=models.IntegerField(default=100, help_text='TopN chart size e.g. 100 or 200'),
        ),
    ]
