# Generated by Django 4.2.30 on 2026-06-19 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0002_artist_country_artist_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=2)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('flag', models.CharField(blank=True, default='', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=80)),
                ('issue_type', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=20)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, default='', max_length=120)),
                ('object_id', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceholderModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='planned', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module', 'title'],
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='artist',
            name='apple_music_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(blank=True, default='solo', max_length=30),
        ),
        migrations.AddField(
            model_name='artist',
            name='audiomack_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='boomplay_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='city_region',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='artist',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='artist',
            name='tiktok_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='x_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certification',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certification',
            name='previous_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlychart',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlychart',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlychart',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_charts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlychart',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='published', max_length=30),
        ),
        migrations.AddField(
            model_name='monthlychart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='breaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='published', max_length=30),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subheadline',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='platform',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='platform',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='platforms/'),
        ),
        migrations.AddField(
            model_name='platform',
            name='max_chart_size',
            field=models.IntegerField(default=50, help_text='Maximum chart rows shown/imported in CMS'),
        ),
        migrations.AddField(
            model_name='platform',
            name='points_method',
            field=models.CharField(blank=True, default='rank_descending', max_length=100),
        ),
        migrations.AddField(
            model_name='platform',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='platform',
            name='supports_albums',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='supports_singles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='release',
            name='apple_music_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='audiomack_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='boomplay_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='release',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='release',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='release',
            name='credited_artists',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='distributor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='release',
            name='featured_artists',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='release',
            name='isrc',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='release',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='release',
            name='number_of_tracks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='producers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='radio_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='shazam_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='songwriters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='spotify_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='release',
            name='tiktok_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='release',
            name='upc',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='release',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='certification',
            name='level',
            field=models.CharField(choices=[('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], max_length=20),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('chart_news', 'Chart News'), ('milestones', 'Milestones'), ('new_releases', 'New Releases'), ('industry_news', 'Industry News'), ('artist_news', 'Artist News'), ('awards', 'Awards'), ('certifications', 'Certifications'), ('records', 'Records'), ('interviews', 'Interviews'), ('editorials', 'Editorials'), ('artist_spotlight', 'Artist Spotlight'), ('albums', 'Albums'), ('analytics', 'Analytics'), ('announcement', 'Announcement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('group', models.CharField(blank=True, default='general', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='MethodologySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v1', max_length=50)),
                ('name', models.CharField(default='Default methodology', max_length=150)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to='cms-media/')),
                ('folder', models.CharField(choices=[('artists', 'Artists'), ('songs', 'Songs'), ('albums', 'Albums'), ('news', 'News'), ('charts', 'Charts'), ('social_cards', 'Social Cards'), ('logos', 'Logos'), ('awards', 'Awards'), ('events', 'Events'), ('general', 'General')], default='general', max_length=40)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('usage_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('singles', 'Singles'), ('albums', 'Albums')], max_length=10)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/cms-charts/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to='uploads/cms-cleaned/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('rolled_back', 'Rolled back')], default='draft', max_length=30)),
                ('rows_data', models.JSONField(blank=True, default=list)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_chart_uploads', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(blank=True, help_text='Blank means combined chart', null=True, on_delete=django.db.models.deletion.SET_NULL, to='charts.platform')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_published_chart_uploads', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], max_length=20, unique=True)),
                ('threshold', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['threshold'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='created', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('module', models.CharField(blank=True, default='', max_length=80)),
                ('object_type', models.CharField(blank=True, default='', max_length=120)),
                ('object_id', models.CharField(blank=True, default='', max_length=80)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_artist_name', models.CharField(max_length=255)),
                ('merged_artist_id', models.PositiveIntegerField(blank=True, null=True)),
                ('moved_releases', models.PositiveIntegerField(default=0)),
                ('aliases_added', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('primary_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_primary_logs', to='charts.artist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('editor', 'Editor'), ('data_editor', 'Data Editor'), ('news_editor', 'News Editor'), ('reviewer', 'Reviewer/Approver'), ('viewer', 'Viewer')], default='viewer', max_length=30)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='admin-users/')),
                ('is_active_editor', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cms_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('level', models.CharField(default='info', max_length=20)),
                ('module', models.CharField(blank=True, default='', max_length=80)),
                ('target_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=80)),
                ('section', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['page', 'display_order'],
                'unique_together': {('page', 'section')},
            },
        ),
    ]
