# Generated by Django 4.2.30 on 2026-07-02 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0013_canonical_chart_methodology'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, help_text="ISO 3166-1 alpha-2 code, e.g. 'KE'", max_length=8)),
                ('rank', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('raw_total_points', models.IntegerField(blank=True, null=True)),
                ('weeks_on_chart', models.IntegerField(default=1)),
                ('platform_count', models.IntegerField(default=1)),
                ('platform_max', models.IntegerField(default=1)),
                ('featured_artists', models.TextField(blank=True, default='')),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, default='', max_length=30)),
                ('peak_rank', models.IntegerField(default=1)),
                ('prev_rank', models.IntegerField(blank=True, help_text='Rank in previous month', null=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_entries', to='charts.monthlychart')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.release')),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['release', 'chart'], name='regional_release_chart_idx'), models.Index(fields=['chart', 'region', 'rank'], name='regional_chart_rank_idx')],
                'unique_together': {('chart', 'region', 'rank')},
            },
        ),
    ]
